poetry.lock, tdp_server/api/dependencies.py, tdp_server/core/config.py, tdp_server/initialize_tdp_vars.py, tdp_server/services/runner.py
Correct how collections are handled since TOSIT-IO/tdp-lib#157
fix #15
=> fix(dependencies): update tdp-lib to latest version

poetry.lock, tdp_server/api/v1/endpoints/deploy.py, tdp_server/api/v1/endpoints/service.py, tdp_server/db/base.py, tdp_server/services/runner.py
=> refactor: upgrade from tdp-lib update

tdp_server/api/v1/endpoints/service.py
=> fix: service not found changed to 404

tdp_server/api/v1/endpoints/deploy.py, tdp_server/schemas/__init__.py, tdp_server/schemas/deployment.py, tdp_server/schemas/operation.py, tdp_server/services/__init__.py, tdp_server/services/deployment_crud.py
=> feat: add deployment information endpoint

poetry.lock, tdp_server/api/dependencies.py, tdp_server/core/config.py, tdp_server/initialize_tdp_vars.py
=> fix: update to tdp-lib last version

tdp_server/api/openid_dependencies.py, tdp_server/core/config.py
=> feat: make token authentication deactivable

tdp_server/core/config.py, tdp_server/services/runner.py
=> feat: make mock deployments possible

tdp_server/db/session.py, tdp_server/models/user_deployment_log.py, tdp_server/schemas/deployment.py, tdp_server/services/deployment_crud.py, tdp_server/services/runner.py
=> fix: return deploying user

poetry.lock, tdp_server/api/v1/endpoints/deploy.py, tdp_server/schemas/deployment.py, tdp_server/schemas/operation.py, tdp_server/services/deployment_crud.py, tdp_server/services/runner.py
Upgrades tdp-server to https://github.com/TOSIT-IO/tdp-lib/commit/6d077b6beab9e3ecc2176b38ad7e01e6ec2ec1eb
=> refactor: upgrade to tdp-lib deployment iterator and fix schema

tdp_server/dump_openapi.py
=> feat: add script to dump openapi definition

tdp_server/models/user_deployment_log.py, tdp_server/services/deployment_crud.py, tdp_server/services/runner.py
=> refactor: rename user attribute not to use keyword

poetry.lock, pyproject.toml, tdp_server/api/dependencies.py, tdp_server/api/v1/endpoints/test_component.py, tdp_server/api/v1/endpoints/test_service.py, tdp_server/conftest.py, tdp_server/core/config.py, tdp_server/test_main.py
First PR to implement tests into tdp_server
=> tests: implement tests for CRUD controller

README.md, docs/quick-start.md
=> docs: install and quick-start instructions

poetry.lock, pyproject.toml, tdp_server/api/dependencies.py, tdp_server/api/v1/endpoints/deploy.py, tdp_server/app.py, tdp_server/conftest.py, tdp_server/dump_openapi.py, tdp_server/main.py, tdp_server/services/runner.py
Fixes None
This PR is a massive internal refactor on how a deployment is managed.
Rework on app creation to hold single instance of library objects
Deployment now runs in an AnyIO worker thread (fastapi async backend) instead of a separate process
To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/), you have to acknowledge this by using the following check-box.
=> refactor: wrap deployment in a future

tdp_server/schemas/deployment.py
Fixes #59
To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/), you have to acknowledge this by using the following check-box.
=> docs: document DeployRequest parameters

tdp_server/app.py
=> feat: enable gzip compression

tdp_server/api/dependencies.py, tdp_server/api/v1/api.py, tdp_server/api/v1/endpoints/deploy.py, tdp_server/api/v1/endpoints/operation.py, tdp_server/app.py, tdp_server/schemas/__init__.py, tdp_server/schemas/deployment.py, tdp_server/schemas/operation.py, tdp_server/services/__init__.py, tdp_server/services/deployment_crud.py, tdp_server/services/operations.py
=> feat: implement operation endpoint

tdp_server/api/v1/endpoints/deploy.py, tdp_server/schemas/__init__.py, tdp_server/schemas/deployment.py, tdp_server/services/deployment_crud.py, tdp_server/services/runner.py, tdp_server/services/utils.py
=> Rename deployment schema to DeploymentLog

tdp_server/services/runner.py
=> fix: do not share sqla session between threads

tdp_server/api/v1/endpoints/deploy.py, tdp_server/schemas/__init__.py, tdp_server/schemas/deployment.py, tdp_server/services/deployment_plan.py
=> feat: add run endpoint

tdp_server/schemas/deployment.py, tdp_server/schemas/operation.py, tdp_server/services/__init__.py, tdp_server/services/deployment_crud.py, tdp_server/services/runner.py, tdp_server/services/utils.py
=> refactor: use pydantic facilities to parse models

poetry.lock, tdp_server/services/runner.py
=> fix: do not insert null operation log

tdp_server/api/v1/endpoints/deploy.py, tdp_server/services/deployment_plan.py
=> feat: implement reconfigure endpoint

tdp_server/api/v1/endpoints/deploy.py, tdp_server/schemas/__init__.py, tdp_server/schemas/deployment.py, tdp_server/services/deployment_plan.py
Fixes #56
This PR is based of branch #57, will rebase once its merged.
Requires:
=> 56 implement resume endpoint

poetry.lock, tdp_server/api/v1/endpoints/deploy.py, tdp_server/schemas/__init__.py, tdp_server/schemas/deployment.py, tdp_server/services/deployment_plan.py
=> feat: rename run to operations

poetry.lock, tdp_server/api/dependencies.py, tdp_server/api/v1/endpoints/deploy.py, tdp_server/app.py, tdp_server/services/__init__.py, tdp_server/services/deployment_plan.py, tdp_server/services/runner.py, tdp_server/services/utils.py
=> refactor: follow runner package rename

docker/entrypoint.sh
=> fix: wait for database readiness

dev/.env-dev, dev/config/init_script.sql
=> refactor: normalize tdp user

tdp_server/api/v1/endpoints/component.py, tdp_server/api/v1/endpoints/service.py, tdp_server/schemas/component.py, tdp_server/schemas/service.py
=> feat: return service or component version

tdp_server/api/v1/endpoints/service.py
=> fix: return component variables when fetching services

poetry.lock, pyproject.toml, tdp_server/api/dependencies.py, tdp_server/api/v1/api.py, tdp_server/api/v1/endpoints/component.py, tdp_server/api/v1/endpoints/schema.py, tdp_server/api/v1/endpoints/service.py, tdp_server/services/variables_crud.py
=> 95 implement schema validation

tdp_server/api/v1/endpoints/deploy.py
=> feat: move deploy endpoint

.gitignore, poetry.lock, tdp_server/api/v1/endpoints/component.py, tdp_server/api/v1/endpoints/service.py, tdp_server/schemas/component.py
Fixes #111 
Also updated the `poetry.lock` file.
=> 111 add serviceid to components return values

tdp_server/api/v1/endpoints/deploy.py
Fixes #105 
I added the reponse model for each endpoints.
=> fix: add schema response to /deploy endpoints

tdp_server/api/v1/endpoints/component.py
Fixes none
Fix the `PUT` method on components variables for deletion.
=> fix: disable merge for put component variables

README.md, docs/quick-start.md
Fixes none
Following [this discussion](https://github.com/orgs/TOSIT-IO/discussions/92)
=> docs: fix naming
